### ISSUE TITLE
compile error in byte-streams when using aleph or gloss

### ISSUE THREAD

**Issue by tgallant** [ztellman/byte-streams#18]
I've been trying to update the dependencies in one of my libraries and a compile error is now being thrown from the byte-streams library.

I tested by removing the requires from the namespace and it seems to be happening when i'm requiring aleph.tcp, gloss.core, or gloss.io

any thoughts?

here is the error:
```clojure
CompilerException java.lang.IllegalAccessError: vector does not exist, compiling:(byte_streams/graph.clj:1:1)
```

current dependencies:
```clojure
[aleph "0.4.0"]
[manifold "0.1.0"]
[gloss "0.2.5"]
```

here is my namespace:
```clojure
(ns mpd-clj.utils
  "utility functions for connecting to the mpd server"
  (:require [clojure.string :as str]
            [manifold.deferred :as d]
            [manifold.stream :as s]
            [aleph.tcp :as tcp]
            [gloss.core :as gloss]
            [gloss.io :as io]))
```

system info:
```clojure
CIDER 0.10.0snapshot (package: 20150801.627) (Java 1.8.0_51, Clojure 1.7.0, nREPL 0.2.7)
```

**Comment by ztellman** [comment]
Try adding `[clj-tuple "0.2.2"]` as an explicit dependency.

**Comment by ztellman** [comment]
I'm fairly sure this was the problem, closing.
