### ISSUE TITLE
to-input-stream not lazy on lazy seqs

### ISSUE THREAD

**Issue by coreasync** [ztellman/byte-streams#21]
Contrary to the https://raw.githubusercontent.com/ztellman/byte-streams/0.2.0/README.md#L37

```
=> (to-input-stream (repeat "hello"))

OutOfMemoryError Requested array size exceeds VM limit  java.util.Arrays.copyOf (Arrays.java:3332)
```

is not lazy.

**Comment by ztellman** [comment]
Thank you for catching this, it should be fixed now in the latest alpha release.
